// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx0EJBs9Tffo6Xivw5BiajEObI5uRIMCs',
    appId: '1:1008830067981:web:54be713fe99874bb476c44',
    messagingSenderId: '1008830067981',
    projectId: 'flipkart-clone-d6b1f',
    authDomain: 'flipkart-clone-d6b1f.firebaseapp.com',
    storageBucket: 'flipkart-clone-d6b1f.appspot.com',
    measurementId: 'G-3XJXLMKXLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZGJlGEmhEqg03q2napgScKouaozzVqZE',
    appId: '1:1008830067981:android:170921283bad02c0476c44',
    messagingSenderId: '1008830067981',
    projectId: 'flipkart-clone-d6b1f',
    storageBucket: 'flipkart-clone-d6b1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ5FbiRp4l-ES4qwMQDVrLhNUsmWLTMy4',
    appId: '1:1008830067981:ios:01ddaa8e78f5ca6f476c44',
    messagingSenderId: '1008830067981',
    projectId: 'flipkart-clone-d6b1f',
    storageBucket: 'flipkart-clone-d6b1f.appspot.com',
    iosClientId: '1008830067981-lekcop7vj9d6eka3oa9qdh5jnudt7g7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flipkartClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ5FbiRp4l-ES4qwMQDVrLhNUsmWLTMy4',
    appId: '1:1008830067981:ios:01ddaa8e78f5ca6f476c44',
    messagingSenderId: '1008830067981',
    projectId: 'flipkart-clone-d6b1f',
    storageBucket: 'flipkart-clone-d6b1f.appspot.com',
    iosClientId: '1008830067981-lekcop7vj9d6eka3oa9qdh5jnudt7g7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flipkartClone',
  );
}
